# Generated by Django 5.0.4 on 2024-04-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_employee_profile_alter_employee_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('number', models.CharField(max_length=20)),
                ('subject', models.TextField(max_length=100)),
                ('details', models.TextField()),
            ],
        ),
    ]
